### ISSUE TITLE
ファイルのヘッダコメント、関数のヘッダコメントをつけてください

### ISSUE THREAD

**Issue by takkkken** [ss-mokumoku/osiete-qiita-kun#7]
https://github.com/ss-mokumoku/osiete-qiita-kun/blob/b951fafc57c44a5f7e436188ee73a1d974bc7613/web_main.php#L3

**Comment by ukyoda** [comment]
関数名が適切でないように思います。

例えば、def関数の関数名には「スタート画面を表示するための関数.」と書かれていますが、
関数の処理内容について書かれていません。

書くとすれば、、、

DBに登録されチエル、最新20件のQiitaの投稿情報を取得する

とかではないでしょうか？

**Comment by takkkken** [comment]
Great Job!
